version: "3.9"
name: clickhouse-facades-example-dapper

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    platform: linux/amd64
    container_name: dapper-example-clickhouse
    restart: unless-stopped
    environment:
      - CLICKHOUSE_USER=example
      - CLICKHOUSE_PASSWORD=example
      - CLICKHOUSE_DB=facades_example
    ports:
      - "38500:8123"