name: Manual testing package release

on:
  workflow_dispatch:
    inputs:
      facades-version:
        type: string
      version:
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Remove Reference
      run: dotnet remove src/ClickHouse.Facades.Testing/ClickHouse.Facades.Testing.csproj reference ../ClickHouse.Facades/ClickHouse.Facades.csproj

    - name: Add Package
      run: dotnet add src/ClickHouse.Facades.Testing/ClickHouse.Facades.Testing.csproj package ClickHouse.Facades --version ${{ github.event.inputs.facades-version }} --no-restore

    - name: Dotnet Restore
      run: dotnet restore src/ClickHouse.Facades.Testing/ClickHouse.Facades.Testing.csproj

    - name: Dotnet Build
      run: dotnet build src/ClickHouse.Facades.Testing/ClickHouse.Facades.Testing.csproj --configuration Release /p:Version=${{ github.event.inputs.version }} --no-restore

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: testing-package
        path: src/ClickHouse.Facades.Testing/bin/Release/ClickHouse.Facades.Testing.*nupkg
