name: Manual templates release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Dotnet Restore
      run: dotnet restore src/ClickHouse.Facades.Templates/ClickHouse.Facades.Templates.csproj

    - name: Dotnet Build
      run: dotnet build src/ClickHouse.Facades.Templates/ClickHouse.Facades.Templates.csproj --configuration Release /p:Version=${{ github.event.inputs.version }} --no-restore

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: templates-package
        path: src/ClickHouse.Facades.Templates/bin/Release/ClickHouse.Facades.Templates.${{ github.event.inputs.version }}.nupkg
      
  push-nuget-org:
    runs-on: ubuntu-latest
    needs: [build]
    name: Push to NuGet.org
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: templates-package
      
    - name: Push Package
      run: dotnet nuget push ClickHouse.Facades.Templates.*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_ORG_API_KEY }} --source https://api.nuget.org/v3/index.json
