name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Dotnet Build
      run: dotnet build src/ClickHouse.Facades/ClickHouse.Facades.csproj --configuration Release /p:Version=${{ github.event.inputs.version }}

    - name: Dotnet Test
      run: dotnet test src/ClickHouse.Facades.Tests/ClickHouse.Facades.Tests.csproj --logger trx --results-directory "TestResults"

    - name: Upload Test Results
      uses: actions/download-artifact@v3
      with:
        name: test-results
        path: TestResults/*.trx

    - name: Upload Package Artifact
      uses: actions/upload-artifact@v3
      with:
        name: facades-package
        path: src/ClickHouse.Facades/bin/Release/ClickHouse.Facades.*nupkg
        
